import { Inter } from 'next/font/google';
import './globals.css';
import Script from 'next/script';
import Head from 'next/head';
import clsx from 'clsx';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://cdn.jsdelivr.net/npm/ionicons@5.5.2/dist/css/ionicons.min.css"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="https://unpkg.com/transition-style" />
      </Head>
      <body className={inter.className}>
        {children}
        <Script src="/public/js/script.js" strategy="afterInteractive" />
        <Script
          type="module"
          src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
        />
      </body>
    </html>
  );
}
